#!/bin/bash

if [[ $# != 1 ]]; then
  echo "Expecting exactly one argument"
  exit 1
fi

EXT="${1##*.}"     # delete longest match from front
FILENAME="${1%.*}" # delete shortest match from back
shift

if [ ${EXT} = cc ]; then
  clang++ -std=c++11 -stdlib=libc++ "${FILENAME}.${EXT}" -o "${FILENAME}" 2> /tmp/tmp
  if [[ $? != 0 ]]; then
    vim /tmp/tmp
  fi
  exit $?
else
  echo "Unknown extension '${EXT}'"
  exit 1
fi
